### ISSUE TITLE
Apresentar nossa ideia para profissionais na área

### ISSUE THREAD

**Issue by Erickjonatthan** [Erickjonatthan/alfa-educa-app#3]

**Comment by DouglasBezerra01** [comment]
![IMG_20241201_224920.jpg](https://github.com/user-attachments/assets/6256a372-4362-48a8-8c3f-b998f555e4c6)

Ótima ideia. É aplicável tanto para o 'público' infantil como para EJA.
Alguns pontos: 
- monitoramento do professor para com o aluno
- aulas independentes [aluno autodidata, a exemplo de adultos que não sabem ler/escrever]
- níveis, indo do alfabeto, para silabação e finalmente para formação de palavras
- em todos os níveis, é de extrema importância que a voz do aplicativo utilize dos fonemas adequadamente

~ Fernando Bezerra das Chagas.

**Comment by DouglasBezerra01** [comment]
Acrescentando:
- caso seja possível, tirar foto da palavra escrita pelo aluno e ver se está escrito corretamente
